<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5vf69pu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5vf69pu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5vf69pu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5vf69pu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5vf69pu\appDevDebugProjectContainer([
    'container.build_hash' => '5vf69pu',
    'container.build_id' => 'fad620c8',
    'container.build_time' => 1552672042,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5vf69pu');
